#include "instructions.h"

#define _InstructionItem(functionName) {reinterpret_cast<intptr_t>(functionName), decltype(GetArgumentCount(functionName))::value, reinterpret_cast<intptr_t>(#functionName)}

const intptr_t Instructions::BY_MICROCODE[270][3] = {
    {0, 0, reinterpret_cast<intptr_t>("halt")}, //Halt instruction
    /*  1*/ _InstructionItem(Instructions::mov_reg_int),
    /*  2*/ _InstructionItem(Instructions::mov_reg_ptr),
    /*  3*/ _InstructionItem(Instructions::mov_reg_regptr),
    /*  4*/ _InstructionItem(Instructions::mov_reg_reg),
    /*  5*/ _InstructionItem(Instructions::mov_ptr_int),
    /*  6*/ _InstructionItem(Instructions::mov_ptr_ptr),
    /*  7*/ _InstructionItem(Instructions::mov_ptr_regptr),
    /*  8*/ _InstructionItem(Instructions::mov_ptr_reg),
    /*  9*/ _InstructionItem(Instructions::mov_regptr_int),
    /* 10*/ _InstructionItem(Instructions::mov_regptr_ptr),
    /* 11*/ _InstructionItem(Instructions::mov_regptr_regptr),
    /* 12*/ _InstructionItem(Instructions::mov_regptr_reg),
    /* 13*/ _InstructionItem(Instructions::jmp_reg),
    /* 14*/ _InstructionItem(Instructions::jmp_ptr),
    /* 15*/ _InstructionItem(Instructions::jmp_regptr),
    /* 16*/ _InstructionItem(Instructions::jmp_int),
    /* 17*/ _InstructionItem(Instructions::cmp_int_int),
    /* 18*/ _InstructionItem(Instructions::cmp_int_ptr),
    /* 19*/ _InstructionItem(Instructions::cmp_int_reg),
    /* 20*/ _InstructionItem(Instructions::cmp_int_regptr),
    /* 21*/ _InstructionItem(Instructions::cmp_ptr_int),
    /* 22*/ _InstructionItem(Instructions::cmp_ptr_ptr),
    /* 23*/ _InstructionItem(Instructions::cmp_ptr_reg),
    /* 24*/ _InstructionItem(Instructions::cmp_ptr_regptr),
    /* 25*/ _InstructionItem(Instructions::cmp_reg_int),
    /* 26*/ _InstructionItem(Instructions::cmp_reg_ptr),
    /* 27*/ _InstructionItem(Instructions::cmp_reg_reg),
    /* 28*/ _InstructionItem(Instructions::cmp_reg_regptr),
    /* 29*/ _InstructionItem(Instructions::cmp_regptr_int),
    /* 30*/ _InstructionItem(Instructions::cmp_regptr_ptr),
    /* 31*/ _InstructionItem(Instructions::cmp_regptr_reg),
    /* 32*/ _InstructionItem(Instructions::cmp_regptr_regptr),
    /* 33*/ _InstructionItem(Instructions::jz_int),
    /* 34*/ _InstructionItem(Instructions::jnz_int),
    /* 35*/ _InstructionItem(Instructions::js_int),
    /* 36*/ _InstructionItem(Instructions::jns_int),
    /* 37*/ _InstructionItem(Instructions::jo_int),
    /* 38*/ _InstructionItem(Instructions::jno_int),
    /* 39*/ _InstructionItem(Instructions::je_int),
    /* 40*/ _InstructionItem(Instructions::jne_int),
    /* 41*/ _InstructionItem(Instructions::jg_int),
    /* 42*/ _InstructionItem(Instructions::jge_int),
    /* 43*/ _InstructionItem(Instructions::jl_int),
    /* 44*/ _InstructionItem(Instructions::jle_int),
    /* 45*/ _InstructionItem(Instructions::add_reg_reg),
    /* 46*/ _InstructionItem(Instructions::add_reg_ptr),
    /* 47*/ _InstructionItem(Instructions::add_reg_regptr),
    /* 48*/ _InstructionItem(Instructions::add_reg_int),
    /* 49*/ _InstructionItem(Instructions::add_ptr_reg),
    /* 50*/ _InstructionItem(Instructions::add_ptr_ptr),
    /* 51*/ _InstructionItem(Instructions::add_ptr_regptr),
    /* 52*/ _InstructionItem(Instructions::add_ptr_int),
    /* 53*/ _InstructionItem(Instructions::add_regptr_reg),
    /* 54*/ _InstructionItem(Instructions::add_regptr_ptr),
    /* 55*/ _InstructionItem(Instructions::add_regptr_regptr),
    /* 56*/ _InstructionItem(Instructions::add_regptr_int),
    /* 57*/ _InstructionItem(Instructions::sub_reg_reg),
    /* 58*/ _InstructionItem(Instructions::sub_reg_ptr),
    /* 59*/ _InstructionItem(Instructions::sub_reg_regptr),
    /* 60*/ _InstructionItem(Instructions::sub_reg_int),
    /* 61*/ _InstructionItem(Instructions::sub_ptr_reg),
    /* 62*/ _InstructionItem(Instructions::sub_ptr_ptr),
    /* 63*/ _InstructionItem(Instructions::sub_ptr_regptr),
    /* 64*/ _InstructionItem(Instructions::sub_ptr_int),
    /* 65*/ _InstructionItem(Instructions::sub_regptr_reg),
    /* 66*/ _InstructionItem(Instructions::sub_regptr_ptr),
    /* 67*/ _InstructionItem(Instructions::sub_regptr_regptr),
    /* 68*/ _InstructionItem(Instructions::sub_regptr_int),
    /* 69*/ _InstructionItem(Instructions::push_reg),
    /* 70*/ _InstructionItem(Instructions::push_ptr),
    /* 71*/ _InstructionItem(Instructions::push_regptr),
    /* 72*/ _InstructionItem(Instructions::push_int),
    /* 73*/ _InstructionItem(Instructions::pop_reg),
    /* 74*/ _InstructionItem(Instructions::pop_ptr),
    /* 75*/ _InstructionItem(Instructions::pop_regptr),
    /* 76*/ _InstructionItem(Instructions::call_int),
    /* 77*/ _InstructionItem(Instructions::call_reg),
    /* 78*/ _InstructionItem(Instructions::call_ptr),
    /* 79*/ _InstructionItem(Instructions::call_regptr),
    /* 80*/ _InstructionItem(Instructions::ret_),
    /* 81*/ _InstructionItem(Instructions::int_int),
    /* 82*/ _InstructionItem(Instructions::int_reg),
    /* 83*/ _InstructionItem(Instructions::int_ptr),
    /* 84*/ _InstructionItem(Instructions::int_regptr),
    /* 85*/ _InstructionItem(Instructions::mul_int),
    /* 86*/ _InstructionItem(Instructions::mul_reg),
    /* 87*/ _InstructionItem(Instructions::mul_ptr),
    /* 88*/ _InstructionItem(Instructions::mul_regptr),
    /* 89*/ _InstructionItem(Instructions::div_int),
    /* 90*/ _InstructionItem(Instructions::div_reg),
    /* 91*/ _InstructionItem(Instructions::div_ptr),
    /* 92*/ _InstructionItem(Instructions::div_regptr),
    /* 93*/ _InstructionItem(Instructions::dec_reg),
    /* 94*/ _InstructionItem(Instructions::dec_ptr),
    /* 95*/ _InstructionItem(Instructions::dec_regptr),
    /* 96*/ _InstructionItem(Instructions::inc_reg),
    /* 97*/ _InstructionItem(Instructions::inc_ptr),
    /* 98*/ _InstructionItem(Instructions::inc_regptr),
    /* 99*/ _InstructionItem(Instructions::neg_reg),
    /*100*/ _InstructionItem(Instructions::neg_ptr),
    /*101*/ _InstructionItem(Instructions::neg_regptr),
    /*102*/ _InstructionItem(Instructions::shl_reg_int),
    /*103*/ _InstructionItem(Instructions::shl_reg_reg),
    /*104*/ _InstructionItem(Instructions::shl_reg_ptr),
    /*105*/ _InstructionItem(Instructions::shl_reg_regptr),
    /*106*/ _InstructionItem(Instructions::shl_ptr_int),
    /*107*/ _InstructionItem(Instructions::shl_ptr_reg),
    /*108*/ _InstructionItem(Instructions::shl_ptr_ptr),
    /*109*/ _InstructionItem(Instructions::shl_ptr_regptr),
    /*110*/ _InstructionItem(Instructions::shl_regptr_int),
    /*111*/ _InstructionItem(Instructions::shl_regptr_reg),
    /*112*/ _InstructionItem(Instructions::shl_regptr_ptr),
    /*113*/ _InstructionItem(Instructions::shl_regptr_regptr),
    /*114*/ _InstructionItem(Instructions::shr_reg_int),
    /*115*/ _InstructionItem(Instructions::shr_reg_reg),
    /*116*/ _InstructionItem(Instructions::shr_reg_ptr),
    /*117*/ _InstructionItem(Instructions::shr_reg_regptr),
    /*118*/ _InstructionItem(Instructions::shr_ptr_int),
    /*119*/ _InstructionItem(Instructions::shr_ptr_reg),
    /*120*/ _InstructionItem(Instructions::shr_ptr_ptr),
    /*121*/ _InstructionItem(Instructions::shr_ptr_regptr),
    /*122*/ _InstructionItem(Instructions::shr_regptr_int),
    /*123*/ _InstructionItem(Instructions::shr_regptr_reg),
    /*124*/ _InstructionItem(Instructions::shr_regptr_ptr),
    /*125*/ _InstructionItem(Instructions::shr_regptr_regptr),
    /*126*/ _InstructionItem(Instructions::not_reg),
    /*127*/ _InstructionItem(Instructions::not_ptr),
    /*128*/ _InstructionItem(Instructions::not_regptr),
    /*129*/ _InstructionItem(Instructions::and_reg_int),
    /*130*/ _InstructionItem(Instructions::and_reg_reg),
    /*131*/ _InstructionItem(Instructions::and_reg_ptr),
    /*132*/ _InstructionItem(Instructions::and_reg_regptr),
    /*133*/ _InstructionItem(Instructions::and_ptr_int),
    /*134*/ _InstructionItem(Instructions::and_ptr_reg),
    /*135*/ _InstructionItem(Instructions::and_ptr_ptr),
    /*136*/ _InstructionItem(Instructions::and_ptr_regptr),
    /*137*/ _InstructionItem(Instructions::and_regptr_int),
    /*138*/ _InstructionItem(Instructions::and_regptr_reg),
    /*139*/ _InstructionItem(Instructions::and_regptr_ptr),
    /*140*/ _InstructionItem(Instructions::and_regptr_regptr),
    /*141*/ _InstructionItem(Instructions::or_reg_int),
    /*142*/ _InstructionItem(Instructions::or_reg_reg),
    /*143*/ _InstructionItem(Instructions::or_reg_ptr),
    /*144*/ _InstructionItem(Instructions::or_reg_regptr),
    /*145*/ _InstructionItem(Instructions::or_ptr_int),
    /*146*/ _InstructionItem(Instructions::or_ptr_reg),
    /*147*/ _InstructionItem(Instructions::or_ptr_ptr),
    /*148*/ _InstructionItem(Instructions::or_ptr_regptr),
    /*149*/ _InstructionItem(Instructions::or_regptr_int),
    /*150*/ _InstructionItem(Instructions::or_regptr_reg),
    /*151*/ _InstructionItem(Instructions::or_regptr_ptr),
    /*152*/ _InstructionItem(Instructions::or_regptr_regptr),
    /*153*/ _InstructionItem(Instructions::xor_reg_int),
    /*154*/ _InstructionItem(Instructions::xor_reg_reg),
    /*155*/ _InstructionItem(Instructions::xor_reg_ptr),
    /*156*/ _InstructionItem(Instructions::xor_reg_regptr),
    /*157*/ _InstructionItem(Instructions::xor_ptr_int),
    /*158*/ _InstructionItem(Instructions::xor_ptr_reg),
    /*159*/ _InstructionItem(Instructions::xor_ptr_ptr),
    /*160*/ _InstructionItem(Instructions::xor_ptr_regptr),
    /*161*/ _InstructionItem(Instructions::xor_regptr_int),
    /*162*/ _InstructionItem(Instructions::xor_regptr_reg),
    /*163*/ _InstructionItem(Instructions::xor_regptr_ptr),
    /*164*/ _InstructionItem(Instructions::xor_regptr_regptr),
    /*165*/ _InstructionItem(Instructions::test_int_int),
    /*166*/ _InstructionItem(Instructions::test_int_ptr),
    /*167*/ _InstructionItem(Instructions::test_int_reg),
    /*168*/ _InstructionItem(Instructions::test_int_regptr),
    /*169*/ _InstructionItem(Instructions::test_ptr_int),
    /*170*/ _InstructionItem(Instructions::test_ptr_ptr),
    /*171*/ _InstructionItem(Instructions::test_ptr_reg),
    /*172*/ _InstructionItem(Instructions::test_ptr_regptr),
    /*173*/ _InstructionItem(Instructions::test_reg_int),
    /*174*/ _InstructionItem(Instructions::test_reg_ptr),
    /*175*/ _InstructionItem(Instructions::test_reg_reg),
    /*176*/ _InstructionItem(Instructions::test_reg_regptr),
    /*177*/ _InstructionItem(Instructions::test_regptr_int),
    /*178*/ _InstructionItem(Instructions::test_regptr_ptr),
    /*179*/ _InstructionItem(Instructions::test_regptr_reg),
    /*180*/ _InstructionItem(Instructions::test_regptr_regptr),
    /*181*/ _InstructionItem(Instructions::rdtsc_),
    /*182*/ _InstructionItem(Instructions::rdtsc_reg),
    /*183*/ _InstructionItem(Instructions::rdtsc_ptr),
    /*184*/ _InstructionItem(Instructions::rdtsc_regptr),
    /*185*/ _InstructionItem(Instructions::xrnd_),
    /*186*/ _InstructionItem(Instructions::xrnd_reg),
    /*187*/ _InstructionItem(Instructions::xrnd_ptr),
    /*188*/ _InstructionItem(Instructions::xrnd_regptr),
    /*189*/ _InstructionItem(Instructions::xtime_),
    /*190*/ _InstructionItem(Instructions::xtime_reg),
    /*191*/ _InstructionItem(Instructions::xtime_ptr),
    /*192*/ _InstructionItem(Instructions::xtime_regptr),
    /*193*/ _InstructionItem(Instructions::xslp_int),
    /*194*/ _InstructionItem(Instructions::xslp_ptr),
    /*195*/ _InstructionItem(Instructions::xslp_reg),
    /*196*/ _InstructionItem(Instructions::xslp_regptr),
    /*197*/ _InstructionItem(Instructions::xwr_int),
    /*198*/ _InstructionItem(Instructions::xwr_reg),
    /*199*/ _InstructionItem(Instructions::xwr_ptr),
    /*200*/ _InstructionItem(Instructions::xwr_regptr),
    /*201*/ _InstructionItem(Instructions::xwr_int_int),
    /*202*/ _InstructionItem(Instructions::xwr_int_reg),
    /*203*/ _InstructionItem(Instructions::xwr_int_ptr),
    /*204*/ _InstructionItem(Instructions::xwr_int_regptr),
    /*205*/ _InstructionItem(Instructions::xwr_reg_int),
    /*206*/ _InstructionItem(Instructions::xwr_reg_reg),
    /*207*/ _InstructionItem(Instructions::xwr_reg_ptr),
    /*208*/ _InstructionItem(Instructions::xwr_reg_regptr),
    /*209*/ _InstructionItem(Instructions::xwr_ptr_int),
    /*210*/ _InstructionItem(Instructions::xwr_ptr_reg),
    /*211*/ _InstructionItem(Instructions::xwr_ptr_ptr),
    /*212*/ _InstructionItem(Instructions::xwr_ptr_regptr),
    /*213*/ _InstructionItem(Instructions::xwr_regptr_int),
    /*214*/ _InstructionItem(Instructions::xwr_regptr_reg),
    /*215*/ _InstructionItem(Instructions::xwr_regptr_ptr),
    /*216*/ _InstructionItem(Instructions::xwr_regptr_regptr),
    /*217*/ _InstructionItem(Instructions::xrd_int_int),
    /*218*/ _InstructionItem(Instructions::xrd_int_reg),
    /*219*/ _InstructionItem(Instructions::xrd_int_ptr),
    /*220*/ _InstructionItem(Instructions::xrd_int_regptr),
    /*221*/ _InstructionItem(Instructions::xrd_reg_int),
    /*222*/ _InstructionItem(Instructions::xrd_reg_reg),
    /*223*/ _InstructionItem(Instructions::xrd_reg_ptr),
    /*224*/ _InstructionItem(Instructions::xrd_reg_regptr),
    /*225*/ _InstructionItem(Instructions::xrd_ptr_int),
    /*226*/ _InstructionItem(Instructions::xrd_ptr_reg),
    /*227*/ _InstructionItem(Instructions::xrd_ptr_ptr),
    /*228*/ _InstructionItem(Instructions::xrd_ptr_regptr),
    /*229*/ _InstructionItem(Instructions::xrd_regptr_int),
    /*230*/ _InstructionItem(Instructions::xrd_regptr_reg),
    /*231*/ _InstructionItem(Instructions::xrd_regptr_ptr),
    /*232*/ _InstructionItem(Instructions::xrd_regptr_regptr),
    /*233*/ _InstructionItem(Instructions::xwi_int),
    /*234*/ _InstructionItem(Instructions::xwi_reg),
    /*235*/ _InstructionItem(Instructions::xwi_ptr),
    /*236*/ _InstructionItem(Instructions::xwi_regptr),
    /*237*/ _InstructionItem(Instructions::xflush_),
    /*238*/ _InstructionItem(Instructions::xts_int_int),
    /*239*/ _InstructionItem(Instructions::xts_int_reg),
    /*240*/ _InstructionItem(Instructions::xts_int_ptr),
    /*241*/ _InstructionItem(Instructions::xts_int_regptr),
    /*242*/ _InstructionItem(Instructions::xts_reg_int),
    /*243*/ _InstructionItem(Instructions::xts_reg_reg),
    /*244*/ _InstructionItem(Instructions::xts_reg_ptr),
    /*245*/ _InstructionItem(Instructions::xts_reg_regptr),
    /*246*/ _InstructionItem(Instructions::xts_ptr_int),
    /*247*/ _InstructionItem(Instructions::xts_ptr_reg),
    /*248*/ _InstructionItem(Instructions::xts_ptr_ptr),
    /*249*/ _InstructionItem(Instructions::xts_ptr_regptr),
    /*250*/ _InstructionItem(Instructions::xts_regptr_int),
    /*251*/ _InstructionItem(Instructions::xts_regptr_reg),
    /*252*/ _InstructionItem(Instructions::xts_regptr_ptr),
    /*253*/ _InstructionItem(Instructions::xts_regptr_regptr),
    /*254*/ _InstructionItem(Instructions::xti_int_int),
    /*255*/ _InstructionItem(Instructions::xti_int_reg),
    /*256*/ _InstructionItem(Instructions::xti_int_ptr),
    /*257*/ _InstructionItem(Instructions::xti_int_regptr),
    /*258*/ _InstructionItem(Instructions::xti_reg_int),
    /*259*/ _InstructionItem(Instructions::xti_reg_reg),
    /*260*/ _InstructionItem(Instructions::xti_reg_ptr),
    /*261*/ _InstructionItem(Instructions::xti_reg_regptr),
    /*262*/ _InstructionItem(Instructions::xti_ptr_int),
    /*263*/ _InstructionItem(Instructions::xti_ptr_reg),
    /*264*/ _InstructionItem(Instructions::xti_ptr_ptr),
    /*265*/ _InstructionItem(Instructions::xti_ptr_regptr),
    /*266*/ _InstructionItem(Instructions::xti_regptr_int),
    /*267*/ _InstructionItem(Instructions::xti_regptr_reg),
    /*268*/ _InstructionItem(Instructions::xti_regptr_ptr),
    /*269*/ _InstructionItem(Instructions::xti_regptr_regptr),
};